// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const BookGenres = sequelize.define('BookGenres', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'BookGenres',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  BookGenres.associate = (models) => {
    BookGenres.belongsTo(models.Books, {
      foreignKey: {
        name: 'bookIdKey',
        field: 'bookId',
      },
      as: 'book',
    });
    BookGenres.belongsTo(models.Genres, {
      foreignKey: {
        name: 'genreIdKey',
        field: 'genreId',
      },
      as: 'genre',
    });
  };

  return BookGenres;
};
